// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYVh9STht1FPQLNyR97uAutcs3CXwT0F4',
    appId: '1:837663621817:web:e1952b454ec690323fd168',
    messagingSenderId: '837663621817',
    projectId: 'fitdiary-58fb1',
    authDomain: 'fitdiary-58fb1.firebaseapp.com',
    storageBucket: 'fitdiary-58fb1.firebasestorage.app',
    measurementId: 'G-LM5G9B8EM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRn4kRr7A81IUY0FkbCYDEGOi_W6FMnMg',
    appId: '1:837663621817:android:6362eeaf463ff6183fd168',
    messagingSenderId: '837663621817',
    projectId: 'fitdiary-58fb1',
    storageBucket: 'fitdiary-58fb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlC_eTWYq0ETq19IUjTiYjTRheGB4RByc',
    appId: '1:837663621817:ios:d172bad03cb979ed3fd168',
    messagingSenderId: '837663621817',
    projectId: 'fitdiary-58fb1',
    storageBucket: 'fitdiary-58fb1.firebasestorage.app',
    iosBundleId: 'com.example.dataPersistenceNetworkingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlC_eTWYq0ETq19IUjTiYjTRheGB4RByc',
    appId: '1:837663621817:ios:d172bad03cb979ed3fd168',
    messagingSenderId: '837663621817',
    projectId: 'fitdiary-58fb1',
    storageBucket: 'fitdiary-58fb1.firebasestorage.app',
    iosBundleId: 'com.example.dataPersistenceNetworkingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYVh9STht1FPQLNyR97uAutcs3CXwT0F4',
    appId: '1:837663621817:web:9e935b12cc2649cf3fd168',
    messagingSenderId: '837663621817',
    projectId: 'fitdiary-58fb1',
    authDomain: 'fitdiary-58fb1.firebaseapp.com',
    storageBucket: 'fitdiary-58fb1.firebasestorage.app',
    measurementId: 'G-5F7J6CXEJP',
  );
}
